### ISSUE TITLE
ci error

### ISSUE THREAD

**Issue by JaeYeopHan** [veccu/react-calendar#22]
```
[semantic-release] › ✖  An error occurred while running semantic-release: RequestError [HttpError]: Validation Failed: {"resource":"ReleaseAsset","code":"already_exists","field":"name"}
    at /home/runner/work/react-calendar/react-calendar/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 422,
```

**Comment by SoYoung210** [comment]
can i take this issue?
